version: '2'

services:
  #proxy-miniature-analog-0:
  #build: .
  #volumes:
  #- /sys/:/sys/
  #network_mode: "host"
  #command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-analog --cid=${CID} --freq=10 --id=1"

    proxy-miniature-gpio-0:
        build: .
        privileged: true    #writing to /sys/
        volumes:
            - /sys/:/sys/
        network_mode: "host"
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-gpio --cid=${CID} --freq=10 --id=1"
    
    proxy-miniature-pwm-0:
        build: .
        privileged: true    #writing to /sys/
        volumes:
            - /sys/:/sys/
        network_mode: "host"
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-pwm --cid=${CID} --id=1"

    proxy-miniature-pwm-1:
        build: .
        privileged: true    #writing to /sys/
        volumes:
            - /sys/:/sys/
        network_mode: "host"
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-pwm --cid=${CID} --id=2"

    proxy-miniature-irdetection-0:
        build: .
        privileged: true    #writing to /sys/
        volumes:
            - /sys/:/sys/
        network_mode: "host"
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-irdetection --cid=${CID} --freq=10 --id=1"

    proxy-miniature-sonar-pru:
        build: .
        privileged: true    #writing to /sys/
        volumes:
            - /dev/:/dev/
        network_mode: "host"
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-sonar-pru --cid=${CID} --freq=2 --id=1"
