.\" Manpage for opendlv-proxy-miniature-irdetection
.\" Author: Group1 SSY190

.TH opendlv-proxy-miniature-irdetection 1 "05 May 2017" "0.1.9" "opendlv-proxy-miniature-irdetection man page"

.SH NAME
opendlv-proxy-miniature-irdetection \- This module handles measurement of IR sensors on the BeagleBone Black.


.SH SYNOPSIS
.B opendlv-proxy-miniature-irdetection --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-proxy-miniature-irdetection --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Group1 SSY190
